name: Release

on: 
  push: 
    branches: 
      - main

jobs:
    render:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v3
            
            - uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Install
              run: npm ci

            - name: Render
              run: npm run build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              env: 
                NODE_ENV: production
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./build
